### ISSUE TITLE
Error demo login

### ISSUE THREAD

**Issue by aaguerra** [casinthecloud/cas-pac4j-oauth-demo#37]
Hi, I'm in this and I don't know how to run the demo.

I followed the readme steps and when I try to log in to the application users. Properties and users do not work.

![image](https://user-images.githubusercontent.com/3911350/28242690-0f085e06-6978-11e7-83a7-75de71f3da19.png)

And I wanted to know if I could advise on the CAS configuration.

I'm putting a startup with a friend and we want to put our app running with CAS but it costs us to configure

**Comment by leleuj** [comment]
Since CAS 5, the configuration has been straightforward using properties: https://github.com/casinthecloud/cas-pac4j-oauth-demo/blob/master/cas-pac4j-oauth-client-demo/src/main/resources/application.properties and https://github.com/casinthecloud/cas-pac4j-oauth-demo/blob/master/cas-pac4j-oauth-server-demo/src/main/resources/application.properties

See: https://apereo.github.io/cas/5.0.x/index.html
